storify/blueprints/account/forms/user.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField, TextAreaField
from wtforms.fields.html5 import EmailField
from wtforms.validators import (DataRequired, Email, EqualTo, Length,
                                ValidationError)
# from flask_wtf.file import FileAllowed, FileField

from storify.blueprints.account.models import User


class EditProfileForm(FlaskForm):
    # username = StringField('Username',
    #                        validators=[DataRequired(), Length(min=2, max=20)])
    first_name = StringField('First name', validators=[Length(min=0, max=60)])
    last_name = StringField('Last name', validators=[Length(min=0, max=60)])
    about = TextAreaField('About me', validators=[Length(min=0, max=140)])
    # picture = FileField('Update Profile Picture', validators=[
    #                     FileAllowed(['jpg', 'png'])])
    date = DateField('Date')
    submit = SubmitField('Save Changes')

    # def validate_username(self, username):
    #     if username.data != current_user.username:
    #         user = User.query.filter_by(username=username.data).first()
    #         if user:
    #             raise ValidationError(
    #                 'That username is taken. Please choose a different one.')


class PasswordChangeForm(FlaskForm):
    old_password = PasswordField('Old password', validators=[DataRequired()])
    password = PasswordField('New password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match.'),
        Length(min=4)])
    password2 = PasswordField('Confirm new password',
                              validators=[DataRequired()])
    submit = SubmitField('Update Password')


class ChangeEmailForm(FlaskForm):
    email = EmailField('New Email', validators=[DataRequired(),
                                                Length(min=1, max=60),
                                                Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Update Email Address')

    def validate_email(self, email):
        if email.data != current_user.email:
            if User.query.filter_by(email=email.data.lower()).first():
                raise ValidationError('Email already registered.')

storify/blueprints/account/views/user.py
from storify.blueprints.account.forms.user import (
    PasswordChangeForm, ChangeEmailForm, EditProfileForm)
from storify.blueprints.account.models import User
from flask_login import current_user, login_required, logout_user
from storify.extensions import db
from storify.utils.email import send_email
from storify.blueprints.story.models import Story
from flask import Blueprint, flash, redirect, render_template, url_for, abort

user = Blueprint('user', __name__,
                 template_folder='../templates', url_prefix='/user/')


@user.route('/<username>/', methods=['GET'])
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    # Latest stories; Recommends; Featured; Drafts; Bookmarks; Comments
    stories = user.stories.order_by(Story.published.desc())
    if user.confirmed is False:
        abort(404)
    return render_template('user/profile.html', user=user, stories=stories)


@user.route('/<username>/recommends/', methods=['GET'])
def recommends(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user/recommends.html', user=user)


@user.route('/stories/', methods=['GET'])
def stories():
    stories = current_user.stories.order_by(Story.published.desc())
    return render_template('user/stories.html', stories=stories)


@user.route('/drafts/', methods=['GET'])
def drafts():

    return render_template('user/drafts.html')


@user.route('/bookmarks/', methods=['GET'])
def bookmarks():

    return render_template('user/bookmarks.html')


@user.route('/settings/', methods=['GET', 'POST'])
@login_required
def settings():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.about = form.about.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.', 'success')
        return redirect(url_for('user.profile', username=current_user.username))
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.about.data = current_user.about
    return render_template('user/settings.html', form=form)


@user.route('/settings/password/', methods=['GET', 'POST'])
@login_required
def password_change():
    """Change an existing user's password."""
    form = PasswordChangeForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            send_email(current_user.email, 'Password Change Notification',
                       'user/email/password_change',
                       user=current_user._get_current_object())
            flash('Your password has been updated.', 'success')
            return redirect(url_for('home'))
        else:
            flash('Original password is invalid. Try again.', 'danger')
    return render_template('user/password_change.html', form=form)


@user.route('/settings/change-email/', methods=['GET', 'POST'])
@login_required
def change_email_request():
    """Respond to existing user's request to change their email."""
    form = ChangeEmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_email = form.email.data.lower()
            token = current_user.generate_email_change_token(new_email)
            send_email(new_email, 'Confirm your email address',
                       'user/email/change_email',
                       user=current_user._get_current_object(), token=token)
            flash(f'A confirmation link has been sent to {new_email}.',
                  'info')
            return redirect(url_for('user.change_email_request'))
        else:
            flash('Invalid email or password.', 'danger')
    return render_template('user/change_email.html', form=form)


@user.route('/settings/change-email/<token>/', methods=['GET', 'POST'])
@login_required
def change_email(token):
    """Change existing user's email with provided token."""
    if current_user.confirm_email_change_token(token):
        db.session.commit()
        flash('Your email address has been updated.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')
    return redirect(url_for('user.profile'))


@user.route('/<username>/follow/')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user:
        flash('You cannot follow yourself!', 'warning')
        return redirect(url_for('user.profile', username=username))
    if current_user.is_following(user):
        flash(f'You are already following {username}.', 'info')
        return redirect(url_for('user.profile', username=username))
    current_user.follow(user)
    # from_user.profile.notify_followed(follow)
    db.session.commit()
    flash(f'You are now following {username}.', 'success')
    return redirect(url_for('user.profile', username=username))


@user.route('/<username>/unfollow/')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user:
        flash('You cannot unfollow yourself!', 'warning')
        return redirect(url_for('user.profile', username=username))
    if not current_user.is_following(user):
        flash(f'You are not following {username}.', 'info')
        return redirect(url_for('user.profile', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(f'You have stopped following {username}.', 'success')
    return redirect(url_for('user.profile', username=username))


@user.route('/<username>/followers/')
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in user.followers.all()]
    return render_template('user/follows.html', user=user, followers=True,
                           title="People followed by ", follows=follows)


@user.route('/<username>/following/')
def following(username):
    user = User.query.filter_by(username=username).first_or_404()
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in user.followed.all()]
    return render_template('user/follows.html', user=user,
                           title="People following ", follows=follows)


@login_required
@user.route('/<username>/disable/')
def disable_acccount(username):
    user = current_user.username
    if request.method == 'POST':
        user.is_active = False
        db.session.commit()
        return logout_user()
    return render_template('user/disable.html', user=user)


@user.route('/<username>/responses/')
def responses(username):
    user = User.query.filter_by(username=username).first_or_404()
    comments = user.user_comments.all()
    return render_template('user/responses.html', comments=comments)


# @login_required
# def notifications(request, username):
#     user = get_object_or_404(User,
#         username=username)
#     notifications = Notification.objects.filter(to_user=request.user)

    # unread = Notification.objects.filter(to_user=request.user, is_read=False)
    # for notification in unread:
    #   notification.is_read = True
    #   notification.save()

    # template = 'accounts/notifications.html'
    # context = {
    #     'user': user,
    #     'notifications': notifications
    # }

    # return render(request, template, context)

storify/blueprints/account/templates/user/change_email.html
{% extends "base.html" %}

{% block title %}Change Email Address {{ super() }}{% endblock %}

{% block content %}

<main class="container mt-5">
    <div class="row">
        {% include "partials/profile_settings_menu.html" %}

        <div class="col-lg-9">
            <h4 class="mb-2 border-bottom pb-3">Change Email Address</h4>

            <div class="row">
                <div class="col-lg-8">
                    <form method="post" action="">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.email.label() }}
                            {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid", placeholder="Enter your new email") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.email(class="form-control", placeholder="Enter your new email") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="col-form-label")}}
                            {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid", placeholder="Enter your password") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.password(class="form-control", placeholder="Enter your password") }}
                            {% endif %}
                        </div>
                        {{ form.submit(class="btn btn-outline-success mr-2")}}
                        <a href="{{ url_for('user.profile', username=current_user.username) }}"
                            class="text-decoration-none">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

storify/blueprints/account/templates/user/drafts.html
{% extends "base.html" %}

{% block title %}My Drafts {{ super() }}{% endblock %}

{% block content %}	
<div class="row mt-5">
	<div class="col-md-12 mb-4">
		<h3>My Drafts</h3>
	</div>

	<div class="col-md-12">
		<ul class="list-unstyled list-inline border-bottom pb-2">
			<li class="list-inline-item mr-3">
				<span class="font-weight-bold">Drafts 2</a>
			</li>
			<li class="list-inline-item">
				<a href="{{ url_for('user.stories') }}" class="text-decoration-none">Published 2</a>
			</li>
		</ul>
				
		{% if drafts %}
			{% for draft in drafts %}
			<div class="flex-md-row mb-4 border-bottom pb-3">
				<div class="d-flex flex-column align-items-start">
					<h5 class="mb-3">Never feel overwhelmed at work again: how to use the M.I.T. technique</h5>              
					<small class="text-muted mb-2">Last edited 7 days ago &bull; 4 min read (6 words) so far</small>
					<small>
						<a href="#" class="text-decoration-none mr-1">Edit</a> &bull; 
						<a href="#" class="text-decoration-none ml-1">Delete</a>
					</small>
				</div>
			</div>
			{% endfor %}
		{% else %}
			<p>You currently don't have any unpublished story.</p>
		{% endif %}
	</div>
</div>
{% endblock %}

storify/blueprints/account/templates/user/follows.html
{% extends "base.html" %}

{% block title %}
{% if followers %}People followed by {{ user.get_screen_name }}{% else %}{% endif %}{{ super() }}{% endblock %}
{% block content %}
<main role="main" class="container mt-3">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            {% include "partials/profile_generic_info.html" %}
            <div class="mt-3">
                <ul class="list-unstyled list-inline border-bottom pb-2">
                    <li class="list-inline-item mr-3">
                        <a href="profile.html" class="text-decoration-none" title="Profile">Profile</a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="favorites.html" class="text-decoration-none" title="Recommends">Recommends</a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="responses.html" class="text-decoration-none" title="Responses">Responses</a>
                    </li>
                </ul>

                <h6 class="py-3">{{ user.get_screen_name }} follows</h6>
                {% set user=follows %}
                {% include "partials/user_list.html" %}

            </div>
        </div>
    </div>
</main>

{% endblock %}

storify/blueprints/account/templates/user/password_change.html
{% extends "base.html" %}

{% block title %}Change password {{ super() }}{% endblock %}

{% block content %}
<main class="container mt-5">
    <div class="row">
        {% include "partials/profile_settings_menu.html" %}

        <div class="col-lg-9">
            <h4 class="mb-2 border-bottom pb-3">Change password</h4>

            <div class="row">
                <div class="col-lg-8">
                    <form method="post" action="">
                        {{ form.hidden_tag() }}
                        <div class="form-group">
                            {{ form.old_password.label(class="col-form-label")}}
                            {% if form.old_password.errors %}
                            {{ form.old_password(class="form-control is-invalid", placeholder="Enter your old password") }}
                            <div class="invalid-feedback">
                                {% for error in form.old_password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.old_password(class="form-control", placeholder="Enter your old password") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="col-form-label")}}
                            {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid", placeholder="Enter your new password") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.password(class="form-control", placeholder="Enter your new password") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.password2.label(class="col-form-label")}}
                            {% if form.password2.errors %}
                            {{ form.password2(class="form-control is-invalid", placeholder="Confirm your new password") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.password(class="form-control", placeholder="Confirm your new password") }}
                            {% endif %}
                        </div>
                        {{ form.submit(class="btn btn-outline-success mr-2")}}
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

storify/blueprints/account/templates/user/profile.html
{% extends "base.html" %}

{% block title %}{{ user.get_screen_name }} {{ super() }}{% endblock %}

{% block content %}

<main role="main" class="container mt-3">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            {% include "partials/profile_generic_info.html" %}
            <div class="mt-3">
                <ul class="list-unstyled list-inline border-bottom pb-2">
                    <li class="list-inline-item mr-3">
                        <span class="font-weight-bold">Profile</span>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="favorites.html" class="text-decoration-none" title="Recommends">Recommends</a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="responses.html" class="text-decoration-none" title="Responses">Responses</a>
                    </li>
                </ul>
                
                {% if featured %}
                <h6 class="py-3">Featured</h6>
                {% include "partials/post_list_right_image.html" %}
                {% endif %}

                <h6 class="py-3">Latest</h6>
                {% include "partials/post_list_right_image.html" %}
                
            </div>
        </div>
    </div>
</main>

{% endblock %}

storify/blueprints/account/templates/user/recommends.html
{% extends "base.html" %}

{% block title %}Stories {{ user.get_screen_name }} Recommends {{ super() }}{% endblock %}

{% block content %}
<main role="main" class="container mt-3">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="row">
                <div class="col-sm-9 order-last order-sm-first">
                    <h3 class="mb-1">
                        {{ user.get_screen_name }}
                        <a href="#" class="mx-2 btn btn-success btn-sm btn-follow">Following</a>
                        <small>
                            <div class="dropdown d-inline">
                                <a title="More actions" data-toggle="dropdown" href="#" role="button"
                                    aria-haspopup="true" aria-expanded="false">
                                    <small><i class="fas fa-angle-down"></i></small>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">Report user</a>
                                    <a class="dropdown-item" href="#">Block user</a>
                                </div>
                            </div>
                        </small>
                    </h3>
                    <span class="badge badge-secondary pb-1 mb-1" title="Seyi Pythonian also follows you">follows
                        you</span>
                    <p class="mb-1">Exercitationem quaerat labore vel consectetur nam veritatis culpa obcaecati
                        mollitia eos, a facilis consequuntur repellendus.</p>
                    <small>Supports Enyimba FC &bull; Writes about <a href="topic.html"
                            class="text-decoration-none">Trafficking</a></small>
                    <p class="pt-2">
                        <span class="mr-2">
                            <a href="follows.html" class="text-decoration-none">3.2k Followers</a>
                        </span>
                        <span class="mr-2">
                            <a href="follows.html" class="text-decoration-none">10 Following</a>
                        </span> &bull;
                        <a href="#" class="ml-2" title="Like on facebook"><i class="fab fa-facebook"></i></a>
                        <a href="#" class="ml-2" title="Follow on twitter"><i class="fab fa-twitter"></i></a>
                        <a href="#" class="ml-2" title="Visit website"><i class="fas fa-link"></i></a>
                    </p>
                </div>
                <div class="col-sm-3 order-first order-sm-last mb-3">
                    <img class="img-fluid rounded-circle" src="images/150x150.png">
                </div>
            </div>
            <div class="mt-3">
                <ul class="list-unstyled list-inline border-bottom pb-2">
                    <li class="list-inline-item mr-3">
                        <a href="{{ url_for('user.profile', username=user.username) }}" class="text-decoration-none" title="Profile">Profile</a>
                    </li>
                    <li class="list-inline-item mr-3">
                        <span class="font-weight-bold">Recommends</span>
                    </li>
                    <li class="list-inline-item mr-3">
                        <a href="responses.html" class="text-decoration-none" title="Responses">Responses</a>
                    </li>
                </ul>

                <h6 class="py-3">Stories {{ user.get_screen_name }} Recommends</h6>

                <div class="card text-center">
                    <div class="card-body">
                        <p class="card-text">{{ user.get_screen_name }} hasn't recommended any story yet. You can check back
                            later to see their latest recommended story.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

storify/blueprints/account/templates/user/settings.html
{% extends "base.html" %}

{% block title %}Profile settings {{ super() }}{% endblock %}

{% block content %}

<main role="main" class="container mt-5">
    <div class="row">
        {% include "partials/profile_settings_menu.html" %}

        <div class="col-lg-9 mb-5">
            <h4 class="mb-2 border-bottom pb-3">Basic information</h4>
            <form method="post" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        {{ form.first_name.label(class="col-form-label") }}
                        {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control is-invalid", placeholder="Enter your first name") }}
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.first_name(class="form-control", placeholder="Enter your first name") }}
                        {% endif %}
                    </div>
                    <div class="form-group col-md-6">
                        {{ form.last_name.label(class="col-form-label") }}
                        {% if form.last_name.errors %}
                        {{ form.last_name(class="form-control is-invalid", placeholder="Enter your last name") }}
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.last_name(class="form-control", placeholder="Enter your last name") }}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    {{ form.about.label(class="col-form-label") }}
                    {% if form.about.errors %}
                    {{ form.about(class="form-control is-invalid", placeholder="Tell us about yourself in 140 characters.") }}
                    <div class="invalid-feedback">
                        {% for error in form.about.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.about(class="form-control", placeholder="Tell us about yourself in 140 characters.") }}
                    {% endif %}
                </div>

                {{ form.submit(class="btn btn-outline-success mr-3")}}
                <a href="{{ url_for('user.profile', username=current_user.username) }}"
                    class="text-decoration-none">Cancel</a>
            </form>
        </div>
    </div>
</main>

{% endblock %}

storify/blueprints/account/templates/user/stories.html
{% extends "base.html" %}

{% block title %}My Published Stories {{ super() }}{% endblock %}

{% block content %}	
<div class="row mt-5">
	<div class="col-md-12 mb-4">
		<h3>My Published Stories</h3>
	</div>
	
	<div class="col-md-12">
		<ul class="list-unstyled list-inline border-bottom pb-2">
			<li class="list-inline-item mr-3">
				<a href="{{ url_for('user.drafts') }}" class="text-decoration-none">Drafts 2</a>
			</li>
			<li class="list-inline-item">
				<span class="font-weight-bold">Published 2</span>
			</li>
		</ul>
		
		{% for story in stories %}
		<div class="flex-md-row mb-4 border-bottom pb-3">
			<div class="d-flex flex-column align-items-start">
				<h5 class="mb-3">
					<a href="{{ url_for('story.detail', id=story.id) }}" class="text-decoration-none">{{ story.title }}</a>
				</h5>              
				<small class="text-muted mb-2">Published {{ moment(story.published).format('LL') }} &bull; 4 min read</small>
				<small>
					<a href="{{ url_for('story.edit', id=story.id) }}" class="text-decoration-none mr-1">Edit</a> &bull; 
					<a href="{{ url_for('story.delete', id=story.id) }}" class="text-decoration-none ml-1">Delete</a>
				</small>
			</div>
		</div>
		{% endfor %}

	</div>
</div>
{% endblock %}