storify/blueprints/account/views/auth.py
from storify.blueprints.account.forms.auth import (
    LoginForm, PasswordResetForm, PasswordResetRequestForm, RegistrationForm)

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from sqlalchemy.exc import IntegrityError
from werkzeug.urls import url_parse
from storify.extensions import db
from storify.utils.email import send_email

from storify.blueprints.account.models import User

auth = Blueprint('auth', __name__,
                 template_folder='../templates', url_prefix='/auth/')


@auth.before_app_request
def before_request():
    """Force user to confirm email before accessing login-required routes."""
    if current_user.is_authenticated:
        current_user.ping()
        if not current_user.confirmed \
                and request.endpoint \
                and request.blueprint != 'auth' \
                and request.endpoint != 'static':
            return redirect(url_for('auth.unconfirmed'))

# Track the last page a user visited
# @app.before_request
# def _last_page_visited():
#      if "current_page" in session:
#      session["last_page"] = session["current_page"]
#      session["current_page"] = request.path


@auth.route('/unconfirmed/')
def unconfirmed():
    """Catch users with unconfirmed emails."""
    if current_user.is_anonymous or current_user.confirmed:
        return redirect(url_for('home'))
    return render_template('auth/unconfirmed.html')


@auth.route('/login/', methods=['GET', 'POST'])
def login():
    """Log in an existing user."""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is None or not user.verify_password(form.password.data):
            flash('Invalid email or password.', 'danger')
            return redirect(url_for('auth.login'))
        login_user(user, remember=form.remember_me.data)
        next = request.args.get('next')
        if not next or url_parse(next).netloc != '':
            next = url_for('home')
        return redirect(next)
    return render_template('auth/login.html', form=form)


@auth.route('/logout/')
@login_required
def logout():
    """Handle requests to the /logout/ route and logs a user out."""
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(request.args.get('next') or url_for('home'))


@auth.route('/signup/', methods=['GET', 'POST'])
def signup():
    """Register a new user, and send them a confirmation email."""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email=form.email.data.lower(),
                    password=form.password.data,
                    favorite_club=form.favorite_club.data)
        db.session.add(user)
        db.session.commit()

        # Require user to confirm email
        token = user.generate_email_confirmation_token()
        send_email(user.email, 'Confirm Your Account',
                   'auth/email/confirm', user=user, token=token)
        flash(
            f'A confirmation email has been sent to {user.email}.', 'warning')

        return redirect(url_for('auth.login'))
    return render_template('auth/signup.html', form=form)


@auth.route('/confirm-account/<token>/')
@login_required
def confirm(token):
    """Confirm new user's account with provided token."""
    if current_user.confirmed:
        flash('Your account has already been confirmed.', 'info')
        return redirect(url_for('home'))
    if current_user.confirm_email_token(token):
        db.session.commit()
        send_email(current_user.email, 'Account Activation Successful',
                   'auth/email/successful',
                   user=current_user._get_current_object())
        flash('Your account has been confirmed.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')
    return redirect(url_for('home'))


@auth.route('/confirm-account/')
@login_required
def resend_confirmation():
    """Resend email confirmation token to a registered user."""
    if current_user.confirmed:
        flash('Your account has already been confirmed.', 'info')
        return redirect(url_for('home'))
    try:
        token = current_user.generate_email_confirmation_token()
        send_email(current_user.email, 'Confirm Your Account',
                   'auth/email/confirm',
                   user=current_user._get_current_object(), token=token)
        flash(
            f'A new confirmation email has been sent to {current_user.email}.',
            'success')
    except IntegrityError:
        flash('Unable to send an email to confirm your email address.',
              'danger')
    return redirect(url_for('auth.login'))


@auth.route('/reset-password/', methods=['GET', 'POST'])
def password_reset_request():
    """Respond to existing user's request to reset their password."""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = PasswordResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user:
            token = user.generate_password_reset_token()
            send_email(user.email, 'Reset Your Password',
                       'auth/email/reset_password',
                       user=user, token=token)
        flash(
            f'Instructions to reset your password '
            'has been sent to {form.email.data}.', 'info')
        return redirect(url_for('auth.login'))
    return render_template('auth/reset_password.html', form=form)


@auth.route('/reset-password/<token>/', methods=['GET', 'POST'])
def password_reset(token):
    """Reset an existing user's password."""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        if User.confirm_password_token(token, form.password.data):
            db.session.commit()
            flash('Your password has been updated. Please log in to continue.',
                  'success')
            return redirect(url_for('auth.login'))
        else:
            flash('The password reset link is an '
                  'invalid or expired token', 'danger')
            return redirect(url_for('home'))
    return render_template('auth/password_reset_confirm.html', form=form)

storify/blueprints/account/views/user.py
from storify.blueprints.account.forms.user import (
    PasswordChangeForm, ChangeEmailForm, EditProfileForm)
from storify.blueprints.account.models import User
from flask_login import current_user, login_required, logout_user
from storify.extensions import db
from storify.utils.email import send_email
from storify.blueprints.story.models import Story
from flask import Blueprint, flash, redirect, render_template, url_for, abort

user = Blueprint('user', __name__,
                 template_folder='../templates', url_prefix='/user/')


@user.route('/<username>/', methods=['GET'])
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    # Latest stories; Recommends; Featured; Drafts; Bookmarks; Comments
    stories = user.stories.order_by(Story.published.desc())
    if user.confirmed is False:
        abort(404)
    return render_template('user/profile.html', user=user, stories=stories)


@user.route('/<username>/recommends/', methods=['GET'])
def recommends(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('user/recommends.html', user=user)


@user.route('/stories/', methods=['GET'])
def stories():
    stories = current_user.stories.order_by(Story.published.desc())
    return render_template('user/stories.html', stories=stories)


@user.route('/drafts/', methods=['GET'])
def drafts():

    return render_template('user/drafts.html')


@user.route('/bookmarks/', methods=['GET'])
def bookmarks():

    return render_template('user/bookmarks.html')


@user.route('/settings/', methods=['GET', 'POST'])
@login_required
def settings():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.about = form.about.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.', 'success')
        return redirect(url_for('user.profile', username=current_user.username))
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.about.data = current_user.about
    return render_template('user/settings.html', form=form)


@user.route('/settings/password/', methods=['GET', 'POST'])
@login_required
def password_change():
    """Change an existing user's password."""
    form = PasswordChangeForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            db.session.commit()
            send_email(current_user.email, 'Password Change Notification',
                       'user/email/password_change',
                       user=current_user._get_current_object())
            flash('Your password has been updated.', 'success')
            return redirect(url_for('home'))
        else:
            flash('Original password is invalid. Try again.', 'danger')
    return render_template('user/password_change.html', form=form)


@user.route('/settings/change-email/', methods=['GET', 'POST'])
@login_required
def change_email_request():
    """Respond to existing user's request to change their email."""
    form = ChangeEmailForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.password.data):
            new_email = form.email.data.lower()
            token = current_user.generate_email_change_token(new_email)
            send_email(new_email, 'Confirm your email address',
                       'user/email/change_email',
                       user=current_user._get_current_object(), token=token)
            flash(f'A confirmation link has been sent to {new_email}.',
                  'info')
            return redirect(url_for('user.change_email_request'))
        else:
            flash('Invalid email or password.', 'danger')
    return render_template('user/change_email.html', form=form)


@user.route('/settings/change-email/<token>/', methods=['GET', 'POST'])
@login_required
def change_email(token):
    """Change existing user's email with provided token."""
    if current_user.confirm_email_change_token(token):
        db.session.commit()
        flash('Your email address has been updated.', 'success')
    else:
        flash('The confirmation link is invalid or has expired.', 'danger')
    return redirect(url_for('user.profile'))


@user.route('/<username>/follow/')
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user:
        flash('You cannot follow yourself!', 'warning')
        return redirect(url_for('user.profile', username=username))
    if current_user.is_following(user):
        flash(f'You are already following {username}.', 'info')
        return redirect(url_for('user.profile', username=username))
    current_user.follow(user)
    # from_user.profile.notify_followed(follow)
    db.session.commit()
    flash(f'You are now following {username}.', 'success')
    return redirect(url_for('user.profile', username=username))


@user.route('/<username>/unfollow/')
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user:
        flash('You cannot unfollow yourself!', 'warning')
        return redirect(url_for('user.profile', username=username))
    if not current_user.is_following(user):
        flash(f'You are not following {username}.', 'info')
        return redirect(url_for('user.profile', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash(f'You have stopped following {username}.', 'success')
    return redirect(url_for('user.profile', username=username))


@user.route('/<username>/followers/')
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in user.followers.all()]
    return render_template('user/follows.html', user=user, followers=True,
                           title="People followed by ", follows=follows)


@user.route('/<username>/following/')
def following(username):
    user = User.query.filter_by(username=username).first_or_404()
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in user.followed.all()]
    return render_template('user/follows.html', user=user,
                           title="People following ", follows=follows)


@login_required
@user.route('/<username>/disable/')
def disable_acccount(username):
    user = current_user.username
    if request.method == 'POST':
        user.is_active = False
        db.session.commit()
        return logout_user()
    return render_template('user/disable.html', user=user)


@user.route('/<username>/responses/')
def responses(username):
    user = User.query.filter_by(username=username).first_or_404()
    comments = user.user_comments.all()
    return render_template('user/responses.html', comments=comments)


# @login_required
# def notifications(request, username):
#     user = get_object_or_404(User,
#         username=username)
#     notifications = Notification.objects.filter(to_user=request.user)

    # unread = Notification.objects.filter(to_user=request.user, is_read=False)
    # for notification in unread:
    #   notification.is_read = True
    #   notification.save()

    # template = 'accounts/notifications.html'
    # context = {
    #     'user': user,
    #     'notifications': notifications
    # }

    # return render(request, template, context)

storify/blueprints/story/views.py
from datetime import datetime
from flask import (Blueprint, render_template, url_for, redirect, abort, flash)
from flask_login import login_required, current_user
from slugify import slugify
from werkzeug import secure_filename
from werkzeug.contrib.atom import AtomFeed
from storify.extensions import db
from storify.blueprints.topic.models import Topic
from .forms import StoryForm
from .models import Story

story = Blueprint('story', __name__, template_folder='templates')


@story.route('/new-story', methods=['GET', 'POST'])
@login_required
def create():
    form = StoryForm()
    if form.validate_on_submit():
        story = Story(body=form.body.data,
                      title=form.title.data,
                      user_id=current_user.id,
                      published=datetime.utcnow(),
                      topic=Topic.query.get(form.topic.data))
        # image_file = request.files['file']
        # filename = secure_filename(image_file.filename)
        # image_file.save(filename)
        db.session.add(story)
        db.session.commit()
        flash(f'Story {story.title} created successfully', 'success')
        return redirect(url_for('story.detail', slug=story.slug))
    return render_template('story/form.html', form=form)

@login_required
@story.route('/story/<slug>/')
def detail(slug):
    story = Story.query.get_or_404(slug=slug)
    form = CommentForm(data={'entry_id': entry.id})
    return render_template('story/detail.html', story=story, form=form)

@login_required
@story.route('/story/<int:id>/edit/', methods=['GET', 'POST'])
def edit(id):
    story = Story.query.get_or_404(id)
    form = StoryForm(obj=story)
    if story.user_id != current_user.id:
        abort(403)
    if form.validate_on_submit():
        story.title = form.title.data
        story.body = form.body.data
        story.updated = datetime.utcnow()
        db.session.add(story)
        db.session.commit()
        return redirect(url_for('story.detail', slug=story.slug))
    return render_template('story/form.html', form=form, story=story)


@login_required
@story.route('/story/<int:id>/delete/', methods=['GET', 'POST'])
def delete(id):
    story = Story.query.get_or_404(id)
    if story.user_id != current_user.id:
        abort(403)
    if request.method == 'POST':
        story.status = Story.DELETED
        db.session.add(story)
        db.session.commit()
    # db.session.delete(story)
        flash('Your post has been deleted', 'success')
        return redirect(url_for('user.stories'))
    return render_template('delete.html', story=story)


@app.route('/feeds/')
def recent_feed():
    """
    View used to create Atom feeds to the blog readers
    """
    feed = AtomFeed(
        'Latest Blog Posts',
        feed_url=request.url,
        url=request.url_root,
        author=request.url_root
    )
    entries = Entry.query.filter(Entry.status == Entry.PUBLISHED).\
        order_by(Entry.created.desc()).limit(15).all()

    for entry in entries:
        feed.add(
            entry.title,
            entry.body,
            content_type='html',
            url=urljoin(request.url_root, url_for(
                'post', slug=entry.slug)),
            updated=entry.updated,
            published=entry.created)

    return feed.get_response()

storify/templates/partials/nav_header.html
<header class="border-bottom py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-3">
            <h3 class="m-0 p-0">
                <a class="text-dark font-weight-bold text-decoration-none" href="{{ url_for('menu.home') }}">FootyStory</a>
            </h3>
        </div>
        <div class="col-9 d-flex justify-content-end align-items-center">
            <a href=""><i class="fas fa-search mr-3" title="Search FootyStory"></i></a>
            <a class="btn btn-sm btn-outline-success mr-3" href="{{ url_for('story.create') }}">Write a story</a>
            {% if current_user.is_authenticated %}
            <a href=""><i class="far fa-bell" title="Notifications"></i></a>
            <div class="dropdown">
                <a class="d-block pl-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false" title="{{ current_user.username }}">
                    <img class="rounded-circle" src="https://placehold.it/32x32" alt="{{ current_user.username }}">
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{ url_for('user.stories') }}">Stories</a>
                    <a class="dropdown-item" href="{{ url_for('user.bookmarks') }}">Bookmarks</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item"
                        href="{{ url_for('user.profile', username=current_user.username) }}">Profile</a>
                    <a class="dropdown-item" href="{{ url_for('user.settings') }}">Settings</a>
                    <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Sign out</a>
                </div>
            </div>
            {% else %}
            <a class="btn btn-sm btn-outline-success mr-3" href="{{ url_for('auth.signup') }}">Register</a>
            <a class="btn btn-sm btn-outline-success" href="{{ url_for('auth.login') }}">Login</a>
            {% endif %}
        </div>
    </div>
</header>

storify/templates/partials/nav_scroller.html
<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <a class="py-2 pr-2 text-muted text-decoration-none" href="{{ url_for('menu.home') }}" title="Home">Home</a>
        <a class="p-2 text-muted text-decoration-none" href="network.html" title="Network">Network</a>
        <a class="p-2 text-muted text-decoration-none" href="latest.html" title="Latest">Latest</a>
        <a class="p-2 text-muted text-decoration-none" href="{{ url_for('menu.popular') }}" title="Popular">Popular</a>
        <a class="p-2 text-muted text-decoration-none" href="{{ url_for('menu.topics') }}" title="Topics">Topics</a>
        <a class="p-2 text-muted text-decoration-none" href="{{ url_for('menu.people') }}" title="People">People</a>
        <a class="p-2 text-muted text-decoration-none" href="recommends.html" title="Recommends">Recommends</a>
        <a class="p-2 text-muted text-decoration-none" href="collections.html" title="Collections">Collections</a>
        <a class="p-2 text-muted text-decoration-none" href="documentaries.html" title="Documentaries">Documentaries</a>
        <a class="py-2 pl-2 text-muted text-decoration-none" href="journals.html" title="Journals">Journals</a>
    </nav>
</div>

storify/templates/partials/post_list_right_image.html
{% for story in stories %}
<div class="card flex-md-row mb-4">
    <div class="card-body d-flex flex-column align-items-start order-last order-md-first">
        <small class="d-inline-block text-uppercase">
            <a href="" class="text-decoration-none">{{ story.topic }}</a>
        </small>
        <h4>
            <a href="{{ url_for('story.detail', id=story.id) }}" class="text-decoration-none">{{ story.title }}</a>
        </h4>
        <p class="mb-auto">{{ story.get_excerpts() }}</p>
        <div class="d-flex mt-3">
            <img class="rounded-circle mr-2" src="https://placehold.it/50x50">
            <div>
                <a href="{{ url_for('user.profile', username=story.author.username) }}" class="d-block text-decoration-none">{{ story.author.get_screen_name }}</a>
                <small class="text-muted" title="Updated {{ moment(story.updated).fromNow() }}.">{{ moment(story.published).format('LL') }} &bull; 4 min
                    read</small>
            </div>
        </div>
    </div>
    <img class="flex-auto d-md-block order-first order-md-last" src="https://placehold.it/200x250">
</div>
{% endfor %}

storify/templates/partials/profile_generic_info.html
<div class="row">
    <div class="col-sm-9 order-last order-sm-first">
        <h3 class="mb-1">
            {{ user.get_screen_name }}
            {% if user != current_user %}
            {% if not current_user.is_following(user) %}
            <a href="{{ url_for('user.follow', username=user.username) }}"
                class="mx-2 btn btn-outline-success btn-sm">Follow</a>
            {% else %}
            <a href="{{ url_for('user.unfollow', username=user.username) }}"
                class="mx-2 btn btn-outline-danger btn-sm">Unfollow</a>
            {% endif %}
            {% endif %}

            {% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
            | <span class="label label-default">Follows you</span>

            <small>
                <div class="dropdown d-inline">
                    <a title="More actions" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                        aria-expanded="false">
                        <small><i class="fas fa-angle-down"></i></small>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="#">Report user</a>
                        <a class="dropdown-item" href="#">Block user</a>
                    </div>
                </div>
            </small>
            {% endif %}
            {% if current_user.is_authenticated and not user != current_user %}
            <a href="{{ url_for('user.settings') }}" class="mx-2 btn btn-outline-secondary btn-sm">Edit Profile</a>
            {% endif %}
        </h3>
        {% if user.about %}
        <p class="mb-1">{{ user.about }}</p>
        {% endif %}
        <small>Supports Enyimba FC &bull; Writes about <a href="topic.html"
                class="text-decoration-none">Trafficking</a>, <a href="topic.html"
                class="text-decoration-none">Officiating</a> and <a href="topic.html"
                class="text-decoration-none">V.A.R</a></small>
        <p class="pt-2">
            <span class="mr-2">
                <a href="{{ url_for('user.followers', username=user.username) }}" class="text-decoration-none">
                    <span class="font-weight-bold">{{ user.followers.count() }}</span> Followers
                </a>
            </span>
            <span class="mr-2">
                <a href="{{ url_for('user.following', username=user.username) }}" class="text-decoration-none">
                    <span class="font-weight-bold">{{ user.followed.count() }}</span> Following
                </a>
            </span> &bull;
            <a href="#" class="ml-2" title="Like on facebook"><i class="fab fa-facebook"></i></a>
            <a href="#" class="ml-2" title="Follow on twitter"><i class="fab fa-twitter"></i></a>
            <a href="#" class="ml-2" title="Visit website"><i class="fas fa-link"></i></a>
        </p>
        <p class="small"><a href="#">Followed by Jennifer Akpala, StarBase FC, Ogudu, Lagos., and 125
                others you follow</a></p>
    </div>
    <div class="col-sm-3 order-first order-sm-last mb-3">
        <img class="img-fluid rounded-circle" src="https://placehold.it/150x150">
    </div>
</div>

storify/templates/partials/profile_settings_menu.html
<div class="col-lg-3 mb-5">
    <div class="list-group">
        <a href="javascript:void(0)" class="list-group-item list-group-item-action disabled bg-light" tabindex="-1"
            aria-disabled="true">Personal Settings</a>
        <a href="{{ url_for('user.settings') }}" class="list-group-item list-group-item-action">Basic
            information</a>
        <a href="{{ url_for('user.change_email_request') }}" class="list-group-item list-group-item-action">Change
            Email</a>
        <a href="{{ url_for('user.password_change') }}" class="list-group-item list-group-item-action">Change
            Password</a>
    </div>
</div>

storify/templates/partials/user_list.html
<div class="media mb-4 pb-3 border-bottom">
    <img class="mr-3 rounded-circle" src="images/50x50.png">
    <div class="media-body">
        <h6><a href="profile.html" class="text-decoration-none">{{ user.get_screen_name }}</a></h6>
        {% if user.about %}<p class="m-0">{{ user.about }}</p>{% endif %}
    </div>
    <div class="float-right">
        <a href="#" class="btn btn-success btn-sm">Following</a>
        {% if user != current_user %}
        {% if not current_user.is_following(user) %}
        <a href="{{ url_for('user.follow', username=user.username) }}" class="btn btn-success btn-sm">Following</a>
        {% else %}
        <a href="{{ url_for('user.unfollow', username=user.username) }}" class="btn btn-danger btn-sm">Unfollow</a>
        {% endif %}
        {% endif %}
    </div>
</div>